name: TradersDemiron
api-version: 1.18
main: kyas.plugin.main
version: 1.0
description: Spawn traders for demiron
commands:
  trader:
    description: Spawn trader
    usage: /trader [metallurg|guns|healer]
    permission: kyasT.trader